version: 0.0
os: linux
files:
  - source: ./surveyshrike-api-0.0.1-SNAPSHOT.jar
    destination: /tmp
  - source: ./application.properties
    destination: /tmp
  - source: ./import.sql
    destination: /tmp
  - source: ./start_application.sh
    destination: /tmp
hooks:
  ApplicationStart:
    - location: start_application.sh
      timeout: 300