version: 0.0
os: linux
files:
  - source: /target/surveyshrike-api-0.0.1-SNAPSHOT.jar
    destination: /tmp
  - source: /src/main/resources/application.properties
    destination: /tmp
  - source: /src/main/resources/import.sql
    destination: /tmp
  - source: /scripts/start_application.sh
    destination: /tmp
hooks:
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: root